### ISSUE TITLE
Génération automatique de Google Forms (sondages)

### ISSUE THREAD

**Issue by iv-stpn** [EFREI-Horizon/HorizonBot#7]
- Commande pour générer un form à partir de commandes et de templates
- Notification automatique dans le channel sondages ou en privé pour proposer de le remplir

**Comment by Spodera** [comment]
Je vais voir s'il existe un module NPM permettant d'automatiser cette tâche

**Comment by Spodera** [comment]
J'ai bien cherché et je comprends que ce n'est pas possible de créer des Google Forms sans passer par leur platforme Google Cloud Console où on doit enregistrer des scripts en Google Apps Script. Donc ce n'est possible de coder cela en JS/TS (Node.js) ou en Python.

Ce n'est pas une solution satifaisante car il faudrait sauvegarder du code sur un serveur distant.

_De la lecture :_

Dans l'API pour node.js, on ne trouve pas une API "Form" :
https://developers.google.com/apis-explorer

Un repo google API pour node.js (pas d'exemple pour google form) avec des exemples:
https://github.com/googleapis/google-api-nodejs-client#google-apis-nodejs-client

Des tutos pour coder en GAS :
https://developers.google.com/apps-script/articles/tutorials

https://developers.google.com/apps-script/reference/forms/

Des réponses :
https://stackoverflow.com/a/49209964/14223224

https://stackoverflow.com/a/37609595/14223224

**Comment by Spodera** [comment]
Donc il faut trouver un autre service (ou tout coder par nous-même ⁉) pour pouvoir automatiser la creation de formulaire.

**Comment by noftaly** [comment]
Dommage :/ merci d'avoir cherché et d'avoir pu donner toutes ces informations :)
